Animations:
  - Name : Idle
    Sprites : assets/textures/mario/characters.png
    StartPoint : [0, 192]
    SpriteSize : [16, 24]
    FrameCount : 1
    FpsSpeed : 0
    MaxDuration : 0
  
  - Name : Walk
    Sprites : assets/textures/mario/characters.png
    StartPoint : [0, 166]
    SpriteSize : [16, 24]
    FrameCount : 2
    FpsSpeed : 4
    MaxDuration : 0

  - Name : UpsideDown
    Sprites : assets/textures/mario/characters.png
    StartPoint : [0, 150]
    SpriteSize : [16, 16]
    FrameCount : 1
    FpsSpeed : 0
    MaxDuration : 0
  
  - Name : AKM
    Sprites : assets/textures/mario/characters.png
    StartPoint : [0, 150]
    SpriteSize : [16, 16]
    FrameCount : 2
    FpsSpeed : 8
    MaxDuration : 0
  
  - Name : Death
    Sprites : assets/textures/mario/characters.png
    StartPoint : [0, 132]
    SpriteSize : [16, 16]
    FrameCount : 2
    FpsSpeed : 6
    MaxDuration : 0
   
   

HorizontalSpeed : 1.5
AKMHorizontalSpeed : 8
DeathTime : 2.5
DeathImpulse : 10
Score : 200
SwapSideSensors :
  - Name : Left sensor
  - Name : Right sensor
DeathSensors :
  - Name : Top sensor