Animations:
  - Name : wRight
    Sprites : assets/textures/mario/characters.png
    StartPoint : [0, 386]
    SpriteSize : [16, 16]
    FrameCount : 3
    FpsSpeed : 10
    MaxDuration : 0 

  - Name : wLeft
    Sprites : assets/textures/mario/characters.png
    StartPoint : [0, 368]
    SpriteSize : [16, 16]
    FrameCount : 3
    FpsSpeed : 10
    MaxDuration : 0 

  - Name : jRight
    Sprites : assets/textures/mario/characters.png
    StartPoint : [0, 350]
    SpriteSize : [16, 16]
    FrameCount : 1
    FpsSpeed : 0
    MaxDuration : 0 

  - Name : jLeft
    Sprites : assets/textures/mario/characters.png
    StartPoint : [0, 332]
    SpriteSize : [16, 16]
    FrameCount : 1
    FpsSpeed : 0
    MaxDuration : 0 

  - Name : iRight
    Sprites : assets/textures/mario/characters.png
    StartPoint : [0, 314]
    SpriteSize : [16, 16]
    FrameCount : 1
    FpsSpeed : 0
    MaxDuration : 0 

  - Name : iLeft
    Sprites : assets/textures/mario/characters.png
    StartPoint : [0, 296]
    SpriteSize : [16, 16]
    FrameCount : 1
    FpsSpeed : 0
    MaxDuration : 0 

  - Name : hit
    Sprites : assets/textures/mario/characters.png
    StartPoint : [0, 280]
    SpriteSize : [16, 16]
    FrameCount : 1
    FpsSpeed : 0
    MaxDuration : 0 

   
    